### ISSUE TITLE
Кэширование

### ISSUE THREAD

**Issue by guitvcer** [guitvcer/nic-shop#7]
Будем использовать базу данных redis для кэширования. Так как он идеально подходит для этой задачи, прост в освоении.

Нужно добавить redis в docker-compose.yml, использовать уже готовый образ из dockerhub. Устанавливаем либу [redis-py](https://github.com/redis/redis-py).

Когда fastapi поднимается, нам надо создать один объект singleton connection в redis и при отключении fastapi - закрывать соединение. Это соединение мы будем в дальнейшем использовать для кэширования http response-а (для улучшения производительности). Нужно найти в документации как этот middleware (именно с fastapi не работал, поэтому быстро подсказать не могу)

Создаем файл web/cache.py и реализовываем пока что две простые функции - `get(key, redis)` и `set(key, value, redis)`. `redis` имеется здесь ввиду connection в redis.

**Comment by olzhic** [comment]
[olzhas cache.zip](https://github.com/user-attachments/files/17702393/olzhas.cache.zip)
